### ISSUE TITLE
Saving config to SCP doesn't work

### ISSUE THREAD

**Issue by turkovda** [QualiSystems/Juniper-JunOS-Switch-Shell-2G#13]
### Issue details

Save command doesn't work because CLI command flow is incorrect.
JunOS does not support command syntax like:
<pre>
root# save "scp://quali:**********@192.X.X.X/JunOS_router-running-290720-070255"
ssh: Could not resolve hostname quali: hostname nor servname provided, or not known
lost connection
Error saving configuration to scp://quali:**********@192.X.X.X/JunOS_router-running-290720-070255
</pre>

Instead of it we need to write password separately:
<pre>
root# save "scp://quali@192.X.X.X"
The authenticity of host '192.X.X.X (192.X.X.X)' can't be established.
ECDSA key fingerprint is SHA256:juH2cj9iJFSHZsFuTgjafAsR0DqYHmb63n3Kn/H5XM4.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '192.X.X.X' (ECDSA) to the list of known hosts.
quali@192.X.X.X's password:
tempfile
Wrote 77 lines of configuration to 'scp://quali@192.X.X.X'
</pre>

### Logs
[JunOS_router--29-Jul-2020--07-02-55.log](https://github.com/QualiSystems/Juniper-JunOS-Switch-Shell-2G/files/5014757/JunOS_router--29-Jul-2020--07-02-55.log)

### Steps to reproduce

1. Install shell and autoload Resource
2. Run save command with SCP destination

### Actual Result:
Save process fails with error
![image](https://user-images.githubusercontent.com/59359491/88816502-25227880-d1c5-11ea-91b5-462188f6541b.png)

**Comment by saklar13** [comment]
fixed in new [cloudshell-networking-juniper](https://github.com/QualiSystems/cloudshell-networking-juniper/releases/tag/5.0.4)
