### ISSUE TITLE
Junos 3.0.0 installation failed

### ISSUE THREAD

**Issue by Costya-Y** [QualiSystems/Juniper-JunOS-Switch-Shell-2G#7]
Cloudshell failed to install Junos 3.0.0 from online pypi due to the cloudshell-core dependency issue

**Comment by Costya-Y** [comment]
After investigation, we decided to discontinue cloudshell-core python package for python 3

**Comment by saklar13** [comment]
Fixed in the new [cloudshell-networking-juniper](https://github.com/QualiSystems/cloudshell-networking-juniper/releases/tag/5.0.3) patch release
